version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    ignore:
      # @types/node should follow .nvmrc Node version so it igores major updates
      - dependency-name: '@types/node'
        update-types:
          - version-update:semver-major
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
